# Generated by Django 5.0.6 on 2024-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_helloword_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelloWord',
            new_name='Mensagem',
        ),
    ]
