# Generated by Django 5.0.6 on 2024-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('principal', '0005_accesslog_referer_accesslog_usuario_agente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permissao_usuario',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.permission'),
        ),
    ]
