# Generated by Django 5.0.6 on 2024-07-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_usuario_grupos_usuario_permissao_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='usuario',
            new_name='usuario_acesso',
        ),
    ]
