# Generated by Django 5.0.6 on 2024-07-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('principal', '0007_rename_usuario_accesslog_usuario_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='permissao_usuario',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='usuario_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.permission'),
        ),
    ]
